# Generated by Django 3.2 on 2021-08-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.CharField(blank=True, max_length=3000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_modified', models.DateTimeField(auto_now=True)),
                ('Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
